### ISSUE TITLE
createorder

### ISSUE THREAD

**Issue by andersonami** [egermano/bitcointoyou#2]
Im trying to implement the createorder function:
BTC2U.prototype.createorder = function(asset, action, amount, price, callback) {
  this._post('createorder.aspx', callback, {'asset': asset, 'action': action, 'amount': amount, 'price':price })
}

but when I run it, I got the error below. See the buffer variable : 
buffer{
  "success": "0",
  "error": "ERROR_LOADING_VARIABLES[asset:|action:|amount:0|price:0]"
}

**Comment by joaokramers** [comment]
Did u solved it? I am having the same problem.

**Comment by egermano** [comment]
This repository is a WIP. Probably it's not functional.

**Comment by joaokramers** [comment]
Solved it. The method is POST but u have to pass the parameters on the URL like a GET
